#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

nodelist=$1
if [ -z $nodelist ]; then
  echo "$(basename $0) nodelist"
  exit 1
fi

# nodes=($(source /etc/profile &>/dev/null; module load slurm; scontrol show hostname ${nodelist}))
nodes=($(python3 ${topdir}/python3-hostlist/hostlist -e ${nodelist}))

export timestamp=$(date '+%Y-%m-%dT%H:%M:%S')

ms=(
/redfish/v1/Chassis/HGX_CPU_0/Sensors/ProcessorModule_0_CPU_0_TempAvg_0
/redfish/v1/Chassis/HGX_CPU_1/Sensors/ProcessorModule_1_CPU_0_TempAvg_0
/redfish/v1/Chassis/HGX_GPU_0/Sensors/HGX_GPU_0_TEMP_1
/redfish/v1/Chassis/HGX_GPU_1/Sensors/HGX_GPU_1_TEMP_1
/redfish/v1/Chassis/HGX_GPU_2/Sensors/HGX_GPU_2_TEMP_1
/redfish/v1/Chassis/HGX_GPU_3/Sensors/HGX_GPU_3_TEMP_1
/redfish/v1/Chassis/PDB_0/Sensors/PDB_0_Inlet_Temp_0
/redfish/v1/Chassis/Riser_Slot1_BlueField_3_Card/Sensors/BF3_Slot_1_Temp
/redfish/v1/Chassis/Riser_Slot2_BlueField_3_Card/Sensors/BF3_Slot_2_Temp
/redfish/v1/Chassis/IO_Board_0/Sensors/IO_Board_0_CX8_0_Port_0_Temp
/redfish/v1/Chassis/IO_Board_0/Sensors/IO_Board_0_CX8_1_Port_0_Temp
/redfish/v1/Chassis/IO_Board_0/Sensors/IO_Board_0_CX8_1_Port_0_Temp
/redfish/v1/Chassis/IO_Board_1/Sensors/IO_Board_1_CX8_1_Port_0_Temp
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_TotalHSC_Power_0
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_LeakDetector_0_ColdPlate
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_LeakDetector_0_Manifold
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_LeakDetector_1_ColdPlate
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_LeakDetector_1_Manifold
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_1_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_1_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_2_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_2_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_3_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_3_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_4_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_4_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_5_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_5_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_6_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_6_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_7_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_7_REAR
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_8_FRONT
/redfish/v1/Chassis/Chassis_0/Sensors/Chassis_0_FAN_8_REAR
)
export MS=$(echo ${ms[@]}|paste -s -d',')
echo "TIMESTAMP,NODE,$(for i in ${ms[*]}; do echo ${i##*/}; done|paste -s -d ',')"

main(){
  node=$1
  bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
  tmpf=$(mktemp --suffix "_${bmc_ip}")
  curl -s -k -u $bmc_username:$bmc_password https://$bmc_ip/redfish/v1/TelemetryService/MetricReports|jq '.Members[]."@odata.id"'|tr -d '"'|while read i; do
    timeout 3 curl -s -k -u $bmc_username:$bmc_password https://$bmc_ip${i}|jq -r '.MetricValues[]|[.Timestamp,.MetricProperty,.MetricValue]|@tsv' | column -t
  done > $tmpf
  ms=($(echo $MS|tr ',' ' '))
  ret=($(
    for i in ${ms[*]}; do grep -w $i $tmpf||echo "$i nan"; done|awk '{print $NF}'|xargs -I {} printf "%.2f\n" {}|paste -s -d ','
  ))
  echo "${timestamp},${node},${ret[*]}"
  rm -f $tmpf
}
export -f main

echo ${nodes[*]} | tr ' ' '\n' | xargs -P 18 -I {} bash -c 'main {}'
