#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
export hostlist=$topdir/hosts.list

nodelist=$1
if [ -z $nodelist ]; then
  echo "$(basename $0) nodelist"
  exit 1
fi

nodes=($(python3 ${topdir}/python3-hostlist/hostlist -e ${nodelist}))

if [ ${#nodes[@]} -eq 0 ]; then
  echo "nodelist is empty"
  exit 1
fi

for node in "${nodes[@]}"; do
  export bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
  query_gb200_bootorder | while read line; do
    echo "$node: $line"
  done
done
