#!/bin/bash

topdir=$(dirname $(realpath $0))
source $topdir/func.sh
export hostlist=$topdir/hosts.list

nodelist=$1
if [ -z $nodelist ]; then
  echo "$(basename $0) nodelist"
  exit 1
fi

nodes=($(python3 ${topdir}/python3-hostlist/hostlist -e ${nodelist}))

export -f get_serial_number
main(){
  node=$1
  bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
  #ret=$(timeout 5 ipmitool -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} fru print 1||echo 'N/A')
  ret=$(timeout 5 bash -c 'get_serial_number'||echo 'N/A')
  echo "$node: $ret"
}
export -f main

echo ${nodes[*]} | tr ' ' '\n' | xargs -P 18 -I {} bash -c "main {}"
