#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

nodelist=$1
if [ -z $nodelist ]; then
  echo "$(basename $0) nodelist"
  exit 1
fi

# nodes=($(source /etc/profile &>/dev/null; module load slurm; scontrol show hostname ${nodelist}))
nodes=($(python3 ${topdir}/python3-hostlist/hostlist -e ${nodelist}))

timestamp=$(date '+%Y-%m-%dT%H:%M:%S')

mon(){
node=$1
bmc_ip=$2
query_firmware|while read line
do
echo "${node}:${timestamp},${line}"
done
}

(
for node in ${nodes[*]}; do
  bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
  mon $node $bmc_ip &
done
wait
) | sort -k1 -t ','
