#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

node=$1
if [ -z $node ]; then
  echo "$(basename $0) nodename" 
  exit 1
fi

bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
export bmc_ip

ping ${bmc_ip} 

