#!/bin/bash


topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

node=$1
if [ -z $node ]; then
  echo "$(basename $0) nodename"
  exit 1
fi


source ./func.sh
hostlist=./hosts.list

node=$1
[ -z "${action}" ] && action=status

bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
export bmc_ip

ipmitool -C 17 -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} sol deactivate
sleep 1
ipmitool -C 17 -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} sol activate

# ssh root@${bmc_ip} -p 2200