#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

node=$1
if [ -z $node ]; then
  echo "$(basename $0) nodename [bmc|hmc|clear]"
  exit 1
fi

bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
export bmc_ip

part=$2
case ${part} in
"hmc") 
  query_hgx_bmc_log_gb200 ${node}
  ;;
"clear")
  clear_hgx_bmc_log_gb200
  clear_sys_bmc_log_gb200
  ;;
*)
  #ipmitool -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} sel list
  query_sys_bmc_log_gb200 ${node}
  ;;
esac
