#!/bin/bash

#for i in {0..3}; do
#  echo $i $(dcgmi nvlink -g $i -e 2>&1 |awk -F '|' '/Malformed Packet Erro/,/Effective BER/{print $2, $3}'|paste -s -d' ' | tr -s ' ')
#done

sensors1=$(dcgmi dmon -l | grep nvlink_bandwidth_l | awk '{print $NF}'|paste -s -d ',' -)
sensors2=$(dcgmi dmon -l | grep nvlink_bandwidth_total | awk '{print $NF}'|paste -s -d ',' -)
sensors3=$(dcgmi dmon -l | grep nvlink.*error.*total | awk '{print $NF}'|paste -s -d ',' -)
dcgmi dmon -e ${sensors1},${sensors2},${sensors3}  -d 1000 | tr -s ' '
