#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
export hostlist=$topdir/hosts.list

nodelist=$1
if [ -z $nodelist ]; then
  echo "$(basename $0) nodelist"
  exit 1
fi

# nodes=($(source /etc/profile &>/dev/null; module load slurm; scontrol show hostname ${nodelist}))
nodes=($(python3 ${topdir}/python3-hostlist/hostlist -e ${nodelist}))

main(){
  node=$1
  nvswitch_bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
  urls=(
    /redfish/v1/Chassis/MGX_NVSwitch_0/Sensors/MGX_NVSwitch_0_TEMP_0
    /redfish/v1/Chassis/MGX_NVSwitch_1/Sensors/MGX_NVSwitch_1_TEMP_0
    /redfish/v1/Chassis/MGX_BMC_0/Sensors/BMC_TEMP
  )
  ret=($(
    for i in ${urls[@]}; do
      timeout 3 curl -s -k -u ${nvswitch_bmc_user}:${nvswitch_bmc_pass}  \
      https://${nvswitch_bmc_ip}${i}|jq -r '.Id,.Reading'|paste -s -d '='
    done|paste -s -d ','
  ))
  echo "${node}: ${ret[*]}"
}
export -f main

echo ${nodes[*]} | tr ' ' '\n' | xargs -P 9 -I {} bash -c 'main {}' #| sort
