#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

node=$1
if [ -z $node ]; then
  echo "$(basename $0) nodename [bmc|hmc|clear]"
  exit 1
fi

nvswitch_bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')

curl -k -s --user "${nvswitch_bmc_user}:${nvswitch_bmc_pass}" "https://${nvswitch_bmc_ip}/redfish/v1/Systems/System_0/LogServices/EventLog/Entries"|jq '.Members[]."Id"'|tr -d '"'|sort -n|tail -n 300|while read i
do
  curl -k -s --user "${nvswitch_bmc_user}:${nvswitch_bmc_pass}" "https://${nvswitch_bmc_ip}/redfish/v1/Systems/System_0/LogServices/EventLog/Entries/${i}"|jq '.Created,.Severity,.Message'|paste - - -|tr -s '[:space:]'
done
