#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

nodelist=$1
if [ -z $nodelist ]; then
  echo "$(basename $0) nodelist"
  exit 1
fi

# nodes=($(source /etc/profile &>/dev/null; module load slurm; scontrol show hostname ${nodelist}))
nodes=($(python3 ${topdir}/python-hostlist/hostlist -e ${nodelist}))

timestamp=$(date '+%Y-%m-%dT%H:%M:%S')

mon(){
node=$1
powershelf_bmc_ip=$2
curl -s -k -u ${powershelf_bmc_user}:${powershelf_bmc_pass} https://${powershelf_bmc_ip}/redfish/v1/UpdateService/FirmwareInventory|jq -r '.Members[]."@odata.id"'|while read i; do
  curl -s -k -u ${powershelf_bmc_user}:${powershelf_bmc_pass} https://${powershelf_bmc_ip}${i}|jq -r '[.Id,.Version]|@tsv'|column -t
done|while read line
do
echo "${node}:${timestamp},${line}"
done
}

(
for node in ${nodes[*]}; do
  powershelf_bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
  mon $node $powershelf_bmc_ip &
done
wait
) | sort -k1 -t ','