#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

node=$1
if [ -z $node ]; then
  echo "$(basename $0) nodename"
  exit 1
fi

action=$2
[ -z "${action}" ] && action=pxe
#pxe   : Force PXE boot
#disk  : Force boot from default Hard-drive
#bios  : Force boot into BIOS Setup
 
bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
export bmc_ip

ipmitool -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} chassis bootdev ${action}

