#!/bin/bash
topdir=$(dirname $(realpath $0))
export PYTHONPATH=${topdir}/dool/usr/local/lib/python3.12/dist-packages:$PYTHONPATH
${topdir}/dool --cpu --mem --top-cpu --top-mem --ib -N $(ls -1 /sys/class/infiniband|sort -n -k2 -t '_'|xargs -I{} echo {}:1|paste -s -d',') --nvidia-gpu -f --nvidia-gpu-mem -f
