#!/bin/bash

topdir=$(dirname $(realpath $0))

source $topdir/func.sh
hostlist=$topdir/hosts.list

node=$1
if [ -z $node ]; then
  echo "$(basename $0) nodename"
  exit 1
fi

action=$2
[ -z "${action}" ] && action=status

bmc_ip=$(grep -w ${node} ${hostlist} | awk '{print $NF}')
export bmc_ip

ipmitool -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} raw 0x3c 0xA2
sleep 60
ipmitool -I lanplus -H ${bmc_ip} -U ${bmc_username} -P ${bmc_password} power on

