#!/bin/bash

duration="${1:-1}"

tmpf=$(mktemp)
dcgmi dmon -l &> $tmpf

#HMMA(Half-precision Matrix Multiply-Accumulate): FP16,BF16,TF32,FP8
#IMMA(Integer Matrix Multiply-Accumulate): INT4,INT8
metrics=(
  sm_clock
  memory_clock
  gpu_temp
  power_usage
  gpu_utilization
  tensor_imma_active
  tensor_hmma_active
  fp64_active
  fp32_active
  mem_copy_utilization
  fb_total
  fb_free
  fb_used
  nvlink_bandwidth_l[0-9]
  nvlink_bandwidth_l[0-9][0-9]
  nvlink_bandwidth_total
  nvlink.*error.*total*
  ecc_sbe_volatile_total
  ecc_dbe_volatile_total
  ecc_sbe_aggregate_total
  ecc_dbe_aggregate_total
  xid_errors
)

sensors=($(
for m in ${metrics[@]}; do
  #echo $m $(awk "/${m} /{print \$NF}" $tmpf)
  echo $(awk "/${m} /{print \$NF}" $tmpf)
done
))
rm -f $tmpf

## Main
header="$(dcgmi dmon -c 1 -e $(echo ${sensors[@]}|tr ' ' ',') | head -n 1|tr -s ' ')"
i=0
while :; do
  if [ $[i%10] -eq 0 ]; then
    printf "%25s %s\n" TIMESTAMP "$header"
  fi
  ts="$(date -Is)"
  dcgmi dmon -c 1 -d $[1000*$duration] -e $(echo ${sensors[@]}|tr ' ' ',') \
    | tail -n +3 | tr -s ' ' | sed 's#GPU \([0-9]\)#GPU_\1#g' | xargs -I {} echo $ts {}
  sleep $duration
  i=$[i+1]
done
